# Generated by Django 4.0.5 on 2022-06-04 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StartUp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointment',
            new_name='Appointments',
        ),
    ]
