# Generated by Django 4.0.5 on 2022-06-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StartUp', '0005_alter_appointment_appointment_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_name',
            field=models.CharField(choices=[('Accommodation', 'Accommodation'), ('Reimbursement', 'Reimbursement'), ('IPR', 'IPR'), ('Procurement', 'Procurement'), ('Lab', 'Lab'), ('Exit & Graduation', 'Exit & Graduation')], default='None', max_length=20, verbose_name='Service Name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='current_stage',
            field=models.CharField(choices=[('Filled', 'Filled'), ('Being Processed', 'Being Processed'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], max_length=20, verbose_name='Current Stage'),
        ),
    ]
