# Generated by Django 4.0.5 on 2022-06-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StartUp', '0006_service_service_name_alter_service_current_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='member_2',
            field=models.CharField(max_length=200, null=True, verbose_name='Member 2'),
        ),
        migrations.AlterField(
            model_name='team',
            name='member_3',
            field=models.CharField(max_length=200, null=True, verbose_name='Member 3'),
        ),
        migrations.AlterField(
            model_name='team',
            name='member_4',
            field=models.CharField(max_length=200, null=True, verbose_name='Member 4'),
        ),
        migrations.AlterField(
            model_name='team',
            name='member_5',
            field=models.CharField(max_length=200, null=True, verbose_name='Member 5'),
        ),
    ]
