# Generated by Django 4.0.5 on 2022-06-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StartUp', '0007_alter_team_member_2_alter_team_member_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='member_2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Member 2'),
        ),
        migrations.AlterField(
            model_name='team',
            name='member_3',
            field=models.CharField(blank=True, max_length=200, verbose_name='Member 3'),
        ),
        migrations.AlterField(
            model_name='team',
            name='member_4',
            field=models.CharField(blank=True, max_length=200, verbose_name='Member 4'),
        ),
        migrations.AlterField(
            model_name='team',
            name='member_5',
            field=models.CharField(blank=True, max_length=200, verbose_name='Member 5'),
        ),
    ]
